spring.application.name=vigi-gate

server.port = 8082

# Vaadin mode
vaadin.productionMode=false

# Virtual thread
spring.threads.virtual.enabled=true

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.jpa.open-in-view=false

# Waktu tunggu koneksi
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

## config logging ##
logging.config=classpath:logback-spring.xml
spring.output.ansi.enabled=ALWAYS
logging.level.org.atmosphere=INFO
logging.level.com.vaadin.flow.server.communication=INFO

## config cloudinary ##
cloudinary.cloud-name=
cloudinary.api-key=
cloudinary.api-secret=
